### ISSUE TITLE
Spell Checking

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/home#1]
Project contains spelling mistakes. You can contribute in this repository by correcting mistakes. 
Either in [README.md](https://github.com/hashirshoaeb/home/blob/master/README.md) or [configurations.json](https://github.com/hashirshoaeb/home/blob/master/src/configurations.json)

**Comment by iprithvitharun** [comment]
I've sent a pull request

**Comment by iprithvitharun** [comment]
@hashirshoaeb I've sent a pull request

**Comment by hashirshoaeb** [comment]
Hey, @iprithvitharun
I have viewed your changes and I really liked it. Also I have added a comment for small changes.
