### ISSUE TITLE
Add Preview thumbnails to recent projects cards

### ISSUE THREAD

**Issue by shaznan** [hashirshoaeb/home#107]
I would suggest to add project thumbnails as it gives a good first impression to your projects and helps the viewer grasp on what the project is about on first sight 🥇

**Comment by hashirshoaeb** [comment]
This is such a nice suggestion. I appreciate your time. I'll surely consider your suggestion in my [new project](https://github.com/hashirshoaeb/portfolio).

But I'm sorry to inform you that this project has been archived. Feel free to make your own version. I'll be happy to showcase your version in my README. Kindly check the Notice [here](https://github.com/hashirshoaeb/home#notice). 

Also I'm currently working on my new portfolio project which is open for contribution. You can find it [here](https://github.com/hashirshoaeb/portfolio). I'm opening this issue there.

**Comment by shaznan** [comment]
great! I'll take a look at your new project and see what I can contribute, cheers!
