### ISSUE TITLE
Add all of your technical skills that you currently know under the skills section

### ISSUE THREAD

**Issue by shaznan** [hashirshoaeb/home#108]
Based on this project, I can already see that you have more skills other than what is listed on your skills section. 

Such as: 
- React Js
- Bootstrap
- SCSS

By adding more skills from your knowledge stack, you can let the recruiters know what your capacity is just by looking at your portfolio page.

**Comment by hashirshoaeb** [comment]
Thank you for your suggestions. I appreciate your time. 
This project has been archived. Feel free to make your own version. I'll be happy to showcase your version in my README. Kindly check the Notice [here](https://github.com/hashirshoaeb/home#notice). 

Also I'm currently working on my new portfolio project which is open for contribution. You can find it [here](https://github.com/hashirshoaeb/portfolio).
