### ISSUE TITLE
Adding new Features to Dev's Portfolio

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/home#11]
There are few things you can do.
- You can make resume button optional.
- Also resume could be a .pdf file or drive link.
- Also you can write logic if number of project on GitHub is zero , then hide the heading.

**Comment by Kishan1029** [comment]
Do you want to make resumes button optional in About me section?

**Comment by Kishan1029** [comment]
I have to added a code to see if file exist or not. That if it exist it will show the button or else print error on console

**Comment by hashirshoaeb** [comment]
Hey @Kishan1029 
Yes yes. :D

**Comment by hashirshoaeb** [comment]
For Contribution,
- Fork this repository,
- Clone the code to your computer.
- Make changes as you want. 
- Commit, Push, and send me Pull Request. 

Happy coding :D

**Comment by Kishan1029** [comment]
I am having trouble with fs.existSync which checks if file exist or not. It says fs is not function do know anything about it

**Comment by Kishan1029** [comment]
I have added code to check if file exist or not

**Comment by hashirshoaeb** [comment]
Hey @Kishan1029 I have looked into your [repo](https://github.com/Kishan1029/home/tree/master). 


<img width="993" alt="Screenshot 2020-04-23 at 12 17 15 AM" src="https://user-images.githubusercontent.com/35165481/80024179-18242800-84f8-11ea-8a7a-2ec8c1290f18.png">

Branch is even with my repo. I think you have not pushed the changes, that you have made locally. 
Here is the [link](https://help.github.com/en/github/using-git/pushing-commits-to-a-remote-repository) that may help you. 

To check this existence of file or conditional importing [link](https://stackoverflow.com/questions/48259512/how-to-check-if-a-pariticular-fileexists-in-reactjs/48264153). I'm not sure, but this may help you.

Further if you are facing any issue. Let me know.
Feel free to share, that's how we learn.


Happy Hacking,
Hashir

**Comment by hashirshoaeb** [comment]
Also, please work on master branch instead of extended branch. extended branch is not for that purpose. So I'm closing your pull request. Cuz you opened it wrong.

**Comment by Kishan1029** [comment]
Sorry I fix and send new pull request.
