### ISSUE TITLE
Unable to update the website after a few months of deployment

### ISSUE THREAD

**Issue by shiyu99** [hashirshoaeb/home#110]
First of all, thank you for sharing your awesome website! I started adapting this template for my personal website a few months ago. I was able to start modifications and deploy to: https://shiyu99.github.io/. 

However, today, when I wanted to continue the modification and deploy the updates to GitHub pages again, I could not make it work. **My localhost copy is updated but the GitHub page stays the same, even though the command line showed up as "published" when I run "npm run custom-deploy" (see picture below).** 
![Run_Custom Deploy](https://user-images.githubusercontent.com/53148393/143785449-40083690-4443-44c2-a827-e2a2b9272af8.PNG)

For reference, I referred to https://github.com/hashirshoaeb/home/blob/master/READMEdocs/custom-deployment.md  and https://github.com/hashirshoaeb/home/blob/master/pages.js when I tried to make deployments. I made updates on the "main" branch locally, then push the updates to remote GitHub. I then used the "npm run build" command, followed by "npm run custom-deploy". I did not update the gh-pages branch manually.

- **This is my pages.js:**

![image](https://user-images.githubusercontent.com/53148393/143785703-edbdc63b-2220-429e-9f9c-c3907e681376.png)

- **This is the script for my package.json:**

![image](https://user-images.githubusercontent.com/53148393/143785731-faddbf0e-7726-4639-b14b-93dc5f348c57.png)

- **This is my deployment history: My attempted deployments today did not show up**
![image](https://user-images.githubusercontent.com/53148393/143785911-c3cbfd12-6152-4eb3-b1a9-e8d52f83ff3f.png)

Could you help me with this issue? Why "npm custom-deploy" did not deploy the website but the command line didn't reflect the reality (cmd said "published" as mentioned before)? 

Thank you so much!!

By the way, my gh-pages branch updated automatically today when I first attempted "npm run custom-deploy"
![image](https://user-images.githubusercontent.com/53148393/143786083-5bc50142-8de7-4d53-95fb-6874e4f5a064.png)

**Comment by shiyu99** [comment]
As a follow up, when I changed the configuration in pages.js from "branch: "gh-pages"" to "branch: "main"", and run build and custom deploy again, I got the error message that the branch already exists. Is this a cache issue, if so, how to solve it?

![image](https://user-images.githubusercontent.com/53148393/143786704-114698d7-9b50-492d-9fef-ac95d37ec087.png)

**Comment by hashirshoaeb** [comment]
I'll look into your issue, and get back to you soon.

**Comment by shiyu99** [comment]
> I'll look into your issue, and get back to you soon.

Thanks, Hashir! Have you been able to identify the issue root cause?

**Comment by hashirshoaeb** [comment]
Hi, I looked into your repo. Seems like you have not pushed your changes. Also I could not find your `shiyu99.github.io` probably you have made it private. 

Since you are deploying to `shiyu99.github.io` use either `master` or `main` as branch name. If you see error that `branch already exists` simply delete the repo and a new empty repo `shiyu99.github.io` and deploy again. 

If you want to use any other branch name then refer to this doc https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

Sorry for the late response. Feel free to reach out if error still persists. I'll try my best you resolve your issue as soon as possible.
Best,
Hashir

**Comment by shiyu99** [comment]
Yeah, I have that repo as private. I just sent you an invite to access the repo. Please check and let me know if you still have an access issue.

I don't know if I should delete the branch, because I've made a lot of personalization to the main branch already. If I delete the branch I will lose all the changes.

Thank you so much for your help thus far! Really appreciate it.

**Comment by hashirshoaeb** [comment]
messaged you on linkedIn.

**Comment by hashirshoaeb** [comment]
(issue resolved)

problem: you cannot publish on private repository. or else you need to own pro subscription.
