### ISSUE TITLE
Failed to compile 'jumbotron', this is depreciated as of bootstrap 5?

### ISSUE THREAD

**Issue by ZacharyHimes** [hashirshoaeb/home#113]
Getting this when i run npm start:

`Failed to compile.

./src/components/home/Skills.jsx
Attempted import error: 'Jumbotron' is not exported from 'react-bootstrap'.`

**Comment by hashirshoaeb** [comment]
please share your node and npm version using following commands

```bash 
npm -v
node -n
```

**Comment by ZacharyHimes** [comment]
npm: 8.1.2
node: v16.13.2

**Comment by hashirshoaeb** [comment]
I'm not actively maintaining this project. It perfectly works with versions below
```
npm: 14.17.3
npm 7.19.1
```
Maybe you need to downgrade your node version to work on this. If you like, feel free to contribute, in making this project compatible with latest versions. Or you can take a look into my other portfolio project.  https://github.com/hashirshoaeb/portfolio

**Comment by hashirshoaeb** [comment]
Fixed in #125 with #126
