### ISSUE TITLE
error due to build

### ISSUE THREAD

**Issue by Sy3Omda** [hashirshoaeb/home#128]
Hi Bro,
i`m facing error as following 
```
$  npm run build

> build
> react-scripts build

Creating an optimized production build...
Failed to compile.

Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (108)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v7.0.1
```
is there some deprecated packages need to update !
i can reproduce this error in nodejs 16 and 18 as well

**Comment by hashirshoaeb** [comment]
Hi, Thanks for reporting. Feel free to fix and create pull request ❤️

**Comment by Sy3Omda** [comment]
Thanks, i have fixed it via purge Nodejs and reinstall v16 which compatible with sass version
