### ISSUE TITLE
Could you please help me with this error?

### ISSUE THREAD

**Issue by manandraj20** [hashirshoaeb/home#141]
<img width="647" alt="issue" src="https://user-images.githubusercontent.com/84122339/215867259-92edc480-b28d-434f-a77a-64204ae4c553.png">

**Comment by Yaser6682** [comment]
No

در تاریخ سه‌شنبه ۳۱ ژانویه ۲۰۲۳،‏ ۲۳:۲۰ Milan anand raj <
***@***.***> نوشت:

**Comment by manandraj20** [comment]
npm 
<img width="227" alt="npmv" src="https://user-images.githubusercontent.com/84122339/215956658-6ec79ba5-bdc6-42b8-b934-c6adbb57a819.png">

**Comment by hashirshoaeb** [comment]
pushed the fix
