### ISSUE TITLE
Navigation Bar, Bootstrap, React

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/home#17]
**Easy to contribute.** Need to making Navigation bar more **beautiful and responsive**, than the existing one. 
<img width="1440" alt="Screenshot 2020-05-05 at 7 43 22 PM" src="https://user-images.githubusercontent.com/35165481/81079218-b789e780-8f08-11ea-847a-b60da48ad291.png">
<img width="1440" alt="Screenshot 2020-05-05 at 7 45 09 PM" src="https://user-images.githubusercontent.com/35165481/81079434-f9b32900-8f08-11ea-8baf-a89809eadbb7.png">

Feel free to share your ideas. :)

**Comment by Tashima42** [comment]
I noticed that the Nav Bar doesn't work on mobile.

**Comment by hashirshoaeb** [comment]
@Tashima42 Thank you for noticing. I'll look into this issue soon.

**Comment by hashirshoaeb** [comment]
> I noticed that the Nav Bar doesn't work on mobile.

@Tashima42 The issue has been fixed.
