### ISSUE TITLE
Upgrade dependencies to latest versions of npm and Node.

### ISSUE THREAD

**Issue by hindav** [hashirshoaeb/home#173]
The statement refers to a compatibility issue where a specific application, library, or tool fails to function properly with the latest versions of **npm** (Node Package Manager) and **Node.js**. This can happen due to outdated dependencies, breaking changes introduced in newer versions, or lack of updates to the tool to support the current versions of npm and Node.js. Resolving such issues often requires updating the tool, adjusting its configurations, or using an older version of npm and Node.js.

![Screenshot 2024-12-19 204946](https://github.com/user-attachments/assets/2b773bd7-1532-4e33-893e-535a10e15ef6)

**Comment by hashirshoaeb** [comment]
Can you share the error you got on command prompt?

**Comment by hashirshoaeb** [comment]
try running after remove this 

```
  "engines": {
    "npm": "^10.2.3",
    "node": "^20.10.0"
  },
  ```
  from package.json

**Comment by smartqy** [comment]
Why I got blank pages after remove "engines". Could you help me to fix this?
`  "engines": {
    "npm": "^10.2.3",
    "node": "^20.10.0"
  },`

[![Image](https://github.com/user-attachments/assets/1a35a7b6-6d60-4f36-924b-3ee1ee896d54)](url)
