### ISSUE TITLE
Adding my portfolio to Readme.md

### ISSUE THREAD

**Issue by justiceserv** [hashirshoaeb/home#21]
I did what you wrote for me in issue section, and it works fine now!
(I wrote in issues section because i do not know how to mention.. and i deleted my previous repo)
Thanks a lot for helping me!

**Comment by hashirshoaeb** [comment]
Hey! 😄 

Glad to hear that my contributions to the open source, somehow ease your day. And Thank you for using my repo. I'll try to include your version in my readme master as soon as possible. After that i'll close this issue. ❤️ 

However you can help me in making this repo more awesome, by sharing this to your mates or endorse it on social media. Feel free to create new issues for feature requests. Also you can create pull requests for the existing issues. 

Best,
Hashir Shoaib 🇵🇰

**Comment by justiceserv** [comment]
Thanks a lot! 
I would gladly share this repo to my teammates

**Comment by hashirshoaeb** [comment]
@justiceserv Check readme please.

**Comment by justiceserv** [comment]
Thanks a lot! Can I close issue?

**Comment by hashirshoaeb** [comment]
Closing it.
