### ISSUE TITLE
Name too big for mobile

### ISSUE THREAD

**Issue by Tashima42** [hashirshoaeb/home#22]
This project is awesome! Thanks for sharing it.

I made my own protifolio and translated the page to brazilian portuguese, but when i was testing on my phone, i noticed that my name was passing the borders of the top section. I solved it changing the `.display-1` on the CSS of the gh-pages branch from 6rem to 5rem, but this isn't the best way, can you help me with this?

**Comment by hashirshoaeb** [comment]
Thank you again. ❤️ 

Can you please explain what do you mean by, "my name was passing the borders of the top section"?

**Comment by hashirshoaeb** [comment]
Also can you translate the content in the readme? i'd like to feature your repo in my readme section. Are you comfortable with it?

**Comment by Tashima42** [comment]
Here are two screenshots of the issue. 
![image](https://user-images.githubusercontent.com/23709916/85765492-8b127080-b6ec-11ea-9381-d347840657bc.png)
![image](https://user-images.githubusercontent.com/23709916/85765506-8f3e8e00-b6ec-11ea-920c-6e2459486460.png)

I will definitely translate in the next few days!

**Comment by hashirshoaeb** [comment]
https://github.com/hashirshoaeb/home/blob/8aa111dd2acf1e07de6e7432f71c40df0cc4970d/src/components/home/MainBody.jsx#L37

For better approach you can edit the above line of code. You can replace **1** in **"display-1"** with **2, 3 or 4** for smaller size. 
For details about bootstrap class and size you can refer this [link](https://getbootstrap.com/docs/4.5/content/typography/#display-headings).
Try this and let me know if it works or still create issue.

For best solution I'll look into its responsiveness later soon. I mean for desktop it should be bigger in size relative to the size on phones.
