### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by Tashima42** [hashirshoaeb/home#24]
Hi, i've been working on a portuguese version of the website.
This is my fork: [Tashima42/home](https://github.com/tashima42/home)

TODO list (feel free to add more itens):
- [x] README
- [x] MainBody
- [x] AboutMe
- [x] ProjectCard
- [x] Footer
- [x] Navbar
- [x]  index/html
- [x] Blog
- [x] package.json 

Se você fala português e inglês, por favor contribua traduzindo e revisando minhas traduções!

**Comment by hashirshoaeb** [comment]
- [ ] editable-stuff/configurations.json, the keys

**Comment by Tashima42** [comment]
> * [ ]  editable-stuff/configurations.json, the keys

@hashirshoaeb Can you explain me?

**Comment by hashirshoaeb** [comment]
> @hashirshoaeb Can you explain me?

 You know data in configuration.json is in json (key, value pairs) format. You can translate the keys in Portuguese.

for example in, 
```json
"backgroundType": "gradient",
```
you can translate "backgroundType". And so on with all the keys in the configuration.json

**Comment by Tashima42** [comment]
I could, but I don't think it's appropriate. For that kind of thing, english is the default, even for Brazilian devs.

**Comment by hashirshoaeb** [comment]
Okay, you can leave it as it is. Once you are done with translation, let me know. I'd like to feature your repo version in my readme.

**Comment by Tashima42** [comment]
This week a friend will review the translation and when everything is right, I will post a new comment and close the issue.

**Comment by hashirshoaeb** [comment]
Best

**Comment by hashirshoaeb** [comment]
After the review process. Edit the Readme.md and Feature your Repo there and open a pull request with the reference of this issue.

**Comment by Tashima42** [comment]
Just finished the revision, how should i feature my repo?

**Comment by hashirshoaeb** [comment]
Make a nice heading (ie Portuguese version) and attach the link of your repo. Heading should come after the showcase heading. Is that cool? You are free to make the readme more beautiful and readable.

**Comment by Tashima42** [comment]
I couldn't make a pull request because I already have a fork, so I created a gist with the README: [https://gist.github.com/Tashima42/37524da1fef87ea20145ec342c54b383](https://gist.github.com/Tashima42/37524da1fef87ea20145ec342c54b383)

**Comment by hashirshoaeb** [comment]
Okay. So I'll open up a pull request and let you review it. Is that fine?

**Comment by Tashima42** [comment]
Just approved the changes, i'm going to close the issue. Thank you for all the help @hashirshoaeb !
Se você tem alguma contribuição, por favor reabra esse problema.
