### ISSUE TITLE
Option to Upload profile picture or use LinkedIn profile picture instead of the Instagram Profile picture

### ISSUE THREAD

**Issue by darshittrevadia** [hashirshoaeb/home#29]
Instagram is not a very formal platform, And the profile picture there is not suitable to be put up on a portfolio website, rather have LinkedIn profile picture or let the user upload their own photograph instead of the Instagram profile picture

**Comment by hashirshoaeb** [comment]
Sure, will look into it. 
Thanks

**Comment by hashirshoaeb** [comment]
If you can fix it, then feel free to create pull request. 😃

**Comment by darshittrevadia** [comment]
> If you can fix it, then feel free to create pull request.

I am still learning web development. I'd like to, but can't. Sorry 

Also, one more thing, when I share the link to my friends, the preview photograph of your website, which I would not want to show. How do I change that too? Thanks a lot!
![preview](https://user-images.githubusercontent.com/68571544/88176943-ae760000-cc45-11ea-9384-14e346fe825f.jpeg)

**Comment by hashirshoaeb** [comment]
**Steps:**
- Navigate to the "public" folder.
- There you will see "social-image.png".
- Delete it.
- Take a screenshot of your version and rename it "social-image.png" and place it there.
- For depth knowledge about "link preview" you can read or google "metadata tags in html or react"


Let me know if it works for you.
Happy coding.

**Comment by darshittrevadia** [comment]
I followed the exact same steps. But still it is showing your social-image.png not mine.

I redid the same thing at least 6 times. And still, it didn't help!! :(

![Screenshot from 2020-07-23 04-53-41](https://user-images.githubusercontent.com/68571544/88238893-8b2c6e80-cca0-11ea-95a0-297f73bfc1fe.png)

It says  the URL is Invalid

![Screenshot from 2020-07-23 04-54-36](https://user-images.githubusercontent.com/68571544/88238965-b616c280-cca0-11ea-8e8d-1fde3e8e8df4.png)

But when I do go to the  [URL](https://darshithtrevadia.github.io/home/social-image.png)  
https://darshithtrevadia.github.io/home/social-image.png, It is very much a valid link!!
Please help me out! Thank you so much!

**Comment by hashirshoaeb** [comment]
hmm, 
Did you build the project after making changes? 
or is it working fine now?

**Comment by hashirshoaeb** [comment]
To get picture from LinkedIn through LinkedIn apis, one requires authorisation and authentication. So we are skipping this for now. Maybe we will reconsider it for the next version.
