### ISSUE TITLE
How to change data shown in preview link. 

### ISSUE THREAD

**Issue by hashirshoaeb** [hashirshoaeb/home#35]
Need to write guideline in README.md about changing preview link data.

**Comment by TowerX** [comment]
@hashirshoaeb Can you elaborate on this? Maybe I can help with this.

**Comment by TowerX** [comment]
@hashirshoaeb I will work on this task tomorrow. I wanted to apologize for the delay.

**Comment by hashirshoaeb** [comment]
Sure.
