### ISSUE TITLE
Whatsapp thumbnail different from the website

### ISSUE THREAD

**Issue by tanmaypandey7** [hashirshoaeb/home#40]
![Screenshot from 2020-08-06 16-48-59](https://user-images.githubusercontent.com/36691630/89526162-f4fe5980-d804-11ea-8aab-10ad13a9edac.png)
Everything has been modified as per the README [here](https://github.com/hashirshoaeb/home/blob/master/READMEdocs/custom-deployment.md)
Not sure why this is happening, any help?

**Comment by hashirshoaeb** [comment]
Hi @tanmaypandey7 

**Steps:**
- Navigate to the "public" folder.
- There you will see "social-image.png".
- Delete it.
- Take a screenshot of your version and rename it "social-image.png" and place it there.
- For depth knowledge about "link preview" you can read or google "metadata tags in html or react"
- Build and deploy the project again.

Let me know if it works for you.
Happy coding.

**Comment by hashirshoaeb** [comment]
Same as #35

**Comment by tanmaypandey7** [comment]
Hi Hashir, thanks for the response. 

I have changed the social-image.png according, built and deployed it as well. 

![Screenshot from 2020-08-06 18-51-09](https://user-images.githubusercontent.com/36691630/89536621-d2287100-d815-11ea-9107-2f8a6c0480f9.png)
However, I am still getting the old social-image.png for some reason. Any idea why that might be happening?
Sorry, I have no idea about react hence asking this.

**Comment by hashirshoaeb** [comment]
@tanmaypandey7 I have looked into your repo https://github.com/tanmaypandey7/tanmaypandey7.github.io and tested your link https://tanmaypandey7.github.io/ here https://www.heymeta.com/url/tanmaypandey7.github.io/ And it is showing me your recent changes as your want.
Attaching some screenshots.
<img width="749" alt="Screenshot 2020-08-06 at 6 48 23 PM" src="https://user-images.githubusercontent.com/35165481/89539608-6b0abc80-d815-11ea-9fc3-469d87b533c3.png">
![IMG_6607](https://user-images.githubusercontent.com/35165481/89539832-b2914880-d815-11ea-9d37-d71fbb5d475c.jpg)

Let me know if it is still not working. 
Have a good day.
Best,
Hashir Shoaib

**Comment by tanmaypandey7** [comment]
Thank you Hashir, it might have been a caching issue or something. It is working for me on other apps. 

Thanks a ton for your help again. Means a lot <3

**Comment by hashirshoaeb** [comment]
Glad to hear that it's working now. Feel free to approach me anytime @tanmaypandey7 ❤️ 
Thank you for forking this repo. ⭐ 

Best,
Hashir Shoaib
