### ISSUE TITLE
Just a heads up 

### ISSUE THREAD

**Issue by guilyx** [hashirshoaeb/home#47]
Hey,

I felt free to add your project here : https://github.com/guilyx/awesome-github-pages-portfolios
It's just a heads up, if you want to remove it/don't want it featured there, do tell.

**Comment by hashirshoaeb** [comment]
Great, Thanks.

**Comment by hashirshoaeb** [comment]
I would suggest you, if you can take a snapshot and make gif of it.
like these:
- https://github.com/hashirshoaeb/home#showcase-
- https://portfoliohub.umihi.co/?page=3

**Comment by guilyx** [comment]
Great idea 💯
