### ISSUE TITLE
Unnecessary code line in top bar

### ISSUE THREAD

**Issue by Ujjwal3009** [hashirshoaeb/home#48]
There is a line showing </harsha> in top bar

**Comment by hashirshoaeb** [comment]
@Ujjwal3009 Can you explain it a bit more?

**Comment by Ujjwal3009** [comment]
![Screenshot_2020-09-16-22-54-56-78](https://user-images.githubusercontent.com/50870185/93371267-b4681600-f86f-11ea-9afb-8277c56ad664.png)
See the top left </harshit>

**Comment by hashirshoaeb** [comment]
Do you mean **"/"** this? in <**Hashir** /> ?? @Ujjwal3009

**Comment by Ujjwal3009** [comment]
Yes
