### ISSUE TITLE
Skills/Picture

### ISSUE THREAD

**Issue by HCury** [hashirshoaeb/home#49]
Good afternoon Hashir,

I am trying to use the template, but would like to know if there is any way to use my GitHub picture or LinkedIn picture instead?

I am also curious about the "Skills" section you have added to your .io. Can you shed some light on how I add that part to mine?

There is also the case where I don't have Facebook/Twitter/Instagram. How do I remove these icons? I was able to remove the picture but the clickable was still there.

And LASTLY (sorry haha), how would I go about adding a new section i.e. work experience. Thanks!

Thanks.

**Comment by hashirshoaeb** [comment]
Hi @HCury 

Thank you for reaching out. I and Ben are working on version 2 of this portfolio template. And we have solved most of your queries there. 
Steps to get those changes:
- Checkout to **new-features** branch https://github.com/hashirshoaeb/home/tree/new-features
    ```bash
           git checkout new-features
    ```
- Make your changes In [home/src/editable-stuff/config.js](https://github.com/hashirshoaeb/home/blob/new-features/src/editable-stuff/config.js). There you will find [**"skills"** section](https://github.com/hashirshoaeb/home/blob/new-features/src/editable-stuff/config.js#L86) as well.
- Yes you can use your Github picture. In [home/src/editable-stuff/config.js line 37](https://github.com/hashirshoaeb/home/blob/new-features/src/editable-stuff/config.js#L37) read the comments. Your github avatar is hosted at https://avatars2.githubusercontent.com/u/42822020 So, 
    ```js
          const about = {
                      show: true,
                      heading: "About Me",
                      imageLink: "https://avatars2.githubusercontent.com/u/42822020",
                      imageSize: 375,
    ```
- We have solved the icon issue as well. Simply remove the objects.
    ```js
           icons: [
              {
                  image: "fa-github",
                  url: "https://github.com/hashirshoaeb",
              },
              {
                  image: "fa-linkedin",
                  url: "https://www.linkedin.com/in/hashirshoaeb/",
              },
           ],
    ```
- To add new section, you can simply create a component and call it in App.js file (I'm assuming that you have basic knowledge of html css and reactjs). To see the implementation of work experience, you can have a look into Ana's version https://github.com/anaashrafi/home , [Here](https://github.com/anaashrafi/home/blob/master/src/components/home/Experience.jsx) is her experience component.

Thank you for using my template. Let me know if you have more questions. I'll be happy to help. 😃 

Best,
Hashir Shoaib

**Comment by HCury** [comment]
Good afternoon Hashir,

Any specific dimensions the "Leadership" pictures should be?

All my images seem to be stretched or squished.

**Comment by hashirshoaeb** [comment]
Hmm, Thank you for pointing this out. I'll add the option to set dimensions in the config.js file. 

For now dimensions are hardcoded, (width="615" height="450")
Either you can crop you images to this size or change width and height in [home/src/components/home/Leadership.jsx](https://github.com/hashirshoaeb/home/blob/new-features/src/components/home/Leadership.jsx) 
[width line 26](https://github.com/hashirshoaeb/home/blob/new-features/src/components/home/Leadership.jsx#L26) 
[height line 27](https://github.com/hashirshoaeb/home/blob/new-features/src/components/home/Leadership.jsx#L27)

Hope this will solve your problem,
Happy Hacking 😃

**Comment by hashirshoaeb** [comment]
Hi @HCury I'm closing this issue now. If you have more questions you can contact me at hashirshoaeb@gmail.com
