### ISSUE TITLE
Responsive?

### ISSUE THREAD

**Issue by pearces17** [hashirshoaeb/home#51]
I check that your deployment come to responsive web, but not the current code on this repository. Can you please update for the responsive one?

**Comment by hashirshoaeb** [comment]
@pearces17 checkout [new-features](https://github.com/hashirshoaeb/home/tree/new-features) branch 😃

**Comment by pearces17** [comment]
i'll check it on next morning do in my timezone, if it still does'nt do the responsive web, any help? i check your deployment so awesome with the responsive

**Comment by hashirshoaeb** [comment]
Yeah sure, I'll be happy to help. 😄

**Comment by pearces17** [comment]
i find out that the https://github.com/hashirshoaeb/home/tree/new-features actually do the responsive web, except when i try to add new components and then i don't know how to keep it responsive. Thankyou so much @hashirshoaeb
