### ISSUE TITLE
Fav icon

### ISSUE THREAD

**Issue by Dinesh101041** [hashirshoaeb/home#57]
Change the fav icon in the tilte bar ,there is icon of react so please change

![image](https://user-images.githubusercontent.com/59551894/94894369-d637de80-04a6-11eb-8f2b-8eb36a8961b0.png)

**Comment by hashirshoaeb** [comment]
Sure, I'd love if you suggest a better favicon.

**Comment by Dinesh101041** [comment]
I suggest keep your picture  that will look nice sir

**Comment by hashirshoaeb** [comment]
Okay I will look into it. Thanks.

**Comment by Dinesh101041** [comment]
welcome sir
