### ISSUE TITLE
Error on Blog Page

### ISSUE THREAD

**Issue by Anu-bhav** [hashirshoaeb/home#62]
Hi Hashir,

I really like the theme and I did deploy an older version of this theme. 
I've learnt reactjs with this theme, when I was customising my website.
You can take a look at it: https://anubhav.xyz/
Github: https://github.com/Anu-bhav/Portfolio

However now I want to enable the blog part of the website. And I cloned the latest version.
Github of the current one: https://github.com/Anu-bhav/website-idea1

I'm having this error:
![image](https://user-images.githubusercontent.com/41940586/100914551-a8920480-34ec-11eb-8eac-858a59d46319.png)

The homepage and the bloglist page are displaying well with the navbar
![image](https://user-images.githubusercontent.com/41940586/100914687-d5461c00-34ec-11eb-95d4-ee38e22e966f.png)

![image](https://user-images.githubusercontent.com/41940586/100914743-e55dfb80-34ec-11eb-8f75-1a64b8dc5aaf.png)

I also don't know why "Blog" on the navbar is blue. 

I also don't know what this line is for:   // const { showBlog, FirstName } = config;

![image](https://user-images.githubusercontent.com/41940586/100915330-a41a1b80-34ed-11eb-95bf-defcc62f57af.png)

Kindly help me fix this error. Once it's fixed, I plan on integrating this project: "https://github.com/Charca/sapper-blog-template" in place of the current blog page.

I'm quite new to reactjs and I want to expand on the blog portion so that I can upload my markdown notes directly into a blog format. 

I just hope that the error is not because of a dumb mistake of mine.

**Comment by hashirshoaeb** [comment]
Hi @Anu-bhav ,
I'm sorry to tell you that the "blog feature" is not ready and is incomplete. I'll be happy if you implement this feature and send pull request to this project. 

However, @telriot If you are free can you help him? 

Best,
Hashir

**Comment by telriot** [comment]
Hi Hashir!

I am sorry but I have started an internship this week and things are going
to be rough for a little while!

Will let you know when I come back to living 😅

Ben

**Comment by hashirshoaeb** [comment]
Yeah sure @telriot 😃

**Comment by Anu-bhav** [comment]
Hi everyone, 

No worries, I'll implement the blog feature.

However I think the error has to do with a bug in the scrolling functions of the navbar. 

I think it's because the navbar effects were supposed to work with a single page layout, and on the blog page, it cannot access the offset when we try scrolling.

I've also encountered the same bug on the blog listing page. When i scroll, i get the error page.

I'll be honest, I'm quite stuck there as I'm new to this technology. I don't really know how to fix the scrolling issue. 

If someone can help me with the scrolling issue, I'll be able to implement the rest.

No pressure @telriot and good luck for your internship.

Thank you both in advance.

**Comment by hashirshoaeb** [comment]
Hmm, I have a busy schedule this month.
But you can comment out the hooks and logic that observe the scrolling position from the code to keep other things working.

Else, I'll try to look into your code if I found time on weekend.

Best,
Hashir

**Comment by Anu-bhav** [comment]
No worries, I just created another netlify for the blog and added it as a subdomain. 

I changed the Navbar blog link to point to my subdomain.
