### ISSUE TITLE
Education and Work Experience Section

### ISSUE THREAD

**Issue by Soham-coder** [hashirshoaeb/home#64]
A section containing education and work experience will be great . Your portfolio is great and perhaps one of the cleanest and minimal there is in the net.

And also a switch between light and dark themes if possible.

Great work!

**Comment by hashirshoaeb** [comment]
@Soham-coder please describe the issue.

**Comment by 1hanzla100** [comment]
I want to add exprience section in this project

**Comment by 1hanzla100** [comment]
@hashirshoaeb  I have successfully added experience section in project and made a pull request. Kindly merge it with master

**Comment by 1hanzla100** [comment]
https://user-images.githubusercontent.com/59178380/104150173-d7a86980-53fa-11eb-83a0-a1b859dae1cd.mp4

**Comment by hashirshoaeb** [comment]
@1hanzla100 i have emailed you at:  hanzla.tauqeer123@gmail.com

**Comment by 1hanzla100** [comment]
hashirshoaeb <https://github.com/hashirshoaeb>  I have successfully added
experience section in project and made a pull request. Kindly merge it with
master branch
