### ISSUE TITLE
I couldn't solve this issue 

### ISSUE THREAD

**Issue by sasankan** [hashirshoaeb/home#73]
TypeError: resumeData is undefined

![Screenshot_2021-03-04 React App](https://user-images.githubusercontent.com/17333099/109950385-74ec9380-7d02-11eb-8bbd-4dc361efe6b0.png)

**Comment by hashirshoaeb** [comment]
Probably you have not followed the step 4 mention in readme. 

-  `Add your resume as <resume.pdf> in place of src/editable-stuff/resume.pdf `

Kindly confirm if you have done this.

**Comment by hashirshoaeb** [comment]
Wait a sec, are you sure this is my code? I do not have `resumeData` anywhere in my project.

**Comment by sasankan** [comment]
Hi Hashir
  I'm extremely sorry. That issue was there because some other file got
mixed up. It was completely my fault. Thank you so much for the code.

Regards
Sasankan
