### ISSUE TITLE
TAB NAME

### ISSUE THREAD

**Issue by Sai999teja** [hashirshoaeb/home#74]
How could I change the tab name?

**Comment by hashirshoaeb** [comment]
In home/src/components/Navbar.jsx

Line: 58, 67 and 82.

https://github.com/hashirshoaeb/home/blob/a69cfff8e24aa55acfc7f45fa9dc98364114f37e/src/components/Navbar.jsx#L58
https://github.com/hashirshoaeb/home/blob/a69cfff8e24aa55acfc7f45fa9dc98364114f37e/src/components/Navbar.jsx#L67
https://github.com/hashirshoaeb/home/blob/a69cfff8e24aa55acfc7f45fa9dc98364114f37e/src/components/Navbar.jsx#L82

**Comment by hashirshoaeb** [comment]
Let me know if that works.

**Comment by hashirshoaeb** [comment]
Hopefully this has solved your query. I'm closing the issue now.
